#!/bin/bash
#
# Usage: script/test

set -e

script/build

docker kill capistrano > /dev/null 2>&1 || true
docker rm   capistrano > /dev/null 2>&1 || true

echo "==> Running test..."
docker run \
  --rm \
  -it \
  --name capistrano \
  -v $PWD/capistrano/.ssh:/capistrano/.ssh \
  quay.io/spesnova/capistrano \
  cap --version

if test $? -eq 0
then
  echo "    Passed :)"
else
  echo "    Failed :("
  exit 1
fi
