# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes extra tasks
require "capistrano/console"
require "capistrano/coreos"

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rb').each { |r| import r }
